import React, { useState } from 'react';
import PublicLayout from '../components/PublicLayout';
import SocialLinks from '../components/SocialLinks';
import { API_URL } from '../config';
import { useLang } from '../data/useLang';
import { useSeo } from '../hooks/useSeo';

export default function ContactPage() {
    const [lang] = useLang(); const es = lang === 'es';
    const [form, setForm] = useState({ name: '', email: '', phone: '', message: '', website: '' });
    const [status, setStatus] = useState('idle'); const [error, setError] = useState('');
    const t = es ? { label: 'Contacto', title: 'Hablemos de lo que necesitás construir.', intro: 'Podés contarme el contexto, el proceso que querés ordenar y el resultado que esperás.', name: 'Nombre', email: 'Email', phone: 'Teléfono (opcional)', message: 'Mensaje', send: 'Enviar mensaje', sending: 'Enviando…', success: 'Mensaje enviado. Te responderé por el medio que indicaste.', fail: 'No pude enviar el mensaje. Revisá los datos e intentá nuevamente.' } : { label: 'Contact', title: 'Let’s talk about what you need to build.', intro: 'Share the context, the process you want to organize, and the outcome you expect.', name: 'Name', email: 'Email', phone: 'Phone (optional)', message: 'Message', send: 'Send message', sending: 'Sending…', success: 'Message sent. I’ll reply through the contact details you provided.', fail: 'The message could not be sent. Check the details and try again.' };
    useSeo({ lang, canonical: 'https://alejomonardez.com/contacto', title: es ? 'Contacto | Alejo Monárdez' : 'Contact | Alejo Monárdez', description: es ? 'Contactá a Alejo Monárdez para conversar sobre sistemas SaaS, backend, APIs, automatización e integraciones.' : 'Contact Alejo Monárdez to discuss SaaS systems, backend, APIs, automation, and integrations.' });
    async function submit(event) { event.preventDefault(); setStatus('sending'); setError(''); try { const response = await fetch(`${API_URL}/contact`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || t.fail); setForm({ name: '', email: '', phone: '', message: '', website: '' }); setStatus('success'); } catch (err) { setError(err instanceof Error ? err.message : t.fail); setStatus('error'); } }
    const inputClass = 'w-full border-b border-white/20 bg-transparent px-0 py-3 text-sm text-white outline-none placeholder:text-white/30 focus:border-white';
    return <PublicLayout><header className="mx-auto max-w-5xl px-5 py-16 text-center sm:px-8 md:py-24"><p className="text-[10px] uppercase tracking-[0.28em] text-white/40">{t.label}</p><h1 className="mt-5 font-serif text-[clamp(3rem,9vw,7rem)] leading-[0.9] tracking-tight">{t.title}</h1><p className="mx-auto mt-8 max-w-2xl text-base leading-7 text-white/60 md:text-lg">{t.intro}</p></header><section className="mx-auto max-w-3xl px-5 pb-20 sm:px-8"><form onSubmit={submit} className="border border-white/10 p-6 md:p-10"><label className="sr-only" htmlFor="contact-name">{t.name}</label><input id="contact-name" name="name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required autoComplete="name" placeholder={t.name} className={inputClass}/><label className="sr-only" htmlFor="contact-email">{t.email}</label><input id="contact-email" name="email" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required autoComplete="email" placeholder={t.email} className={`${inputClass} mt-5`}/><label className="sr-only" htmlFor="contact-phone">{t.phone}</label><input id="contact-phone" name="phone" type="tel" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} autoComplete="tel" placeholder={t.phone} className={`${inputClass} mt-5`}/><label className="sr-only" htmlFor="contact-message">{t.message}</label><textarea id="contact-message" name="message" rows="6" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} required placeholder={t.message} className={`${inputClass} mt-5 resize-y`}/><input name="website" value={form.website} onChange={e => setForm({ ...form, website: e.target.value })} tabIndex="-1" autoComplete="off" aria-hidden="true" className="absolute -left-[9999px]"/><div className="mt-7 flex flex-wrap items-center justify-between gap-4"><div aria-live="polite" className="text-sm">{status === 'success' && <span className="text-emerald-300">{t.success}</span>}{status === 'error' && <span className="text-red-300">{error || t.fail}</span>}</div><button type="submit" disabled={status === 'sending'} className="min-h-11 rounded-full bg-white px-6 py-3 text-[10px] font-bold uppercase tracking-[0.2em] text-brand-bg disabled:opacity-50">{status === 'sending' ? t.sending : t.send}</button></div></form><SocialLinks className="mt-10 justify-center" /></section></PublicLayout>;
}
